{% set name = "brotlicffi" %}
{% set version = "1.2.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e0fbd13644cf1f6015e75fa5e0ad8fdce1048d9c9ff90b0ce826174b249ee35

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - cffi >=1.0.0
    - pip
    - python
    - setuptools
  run:
    - cffi >=1.0.0
    - enum34  # [py<34]
    - python

test:
  imports:
    - brotlicffi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-hyper/brotlicffi
  summary: Python CFFI bindings to the Brotli library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - sethmlarson
