{% set name = "brotlicffi" %}
{% set version = "1.1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b77827a689905143f87915310b93b273ab17888fd43ef350d4832c4a71083c13

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cffi >=1.0.0
    - pip
    - python
  run:
    - cffi >=1.0.0
    - enum34  # [py<34]
    - python

test:
  imports:
    - brotlicffi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-hyper/brotlicffi
  summary: Python CFFI bindings to the Brotli library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - sethmlarson
